services:
  wallet-app:
    image: wallet-api
    build: .
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - wallet-postgres-db
  wallet-postgres-db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - ${DB_PORT}:5432

